#ifndef __Run__
#define __Run__

/**
@file
Subclass of RunDlg, which is generated by wxFormBuilder.
*/

#include "RunDcpDlg.h"
#include <string>
#include <fstream>
#include <iostream>
#include <vector>
using namespace std;

#ifndef MAX_PATH
#define MAX_PATH 512
#endif
//// end generated include

/** Implementing RunDlg */
class Run : public RunDlg
{
	protected:
		// Handlers for RunDlg events.
		void RunDcpPlayerDlgOnInitDialog( wxInitDialogEvent& event );
		void m_dirPicker2OnDirChanged( wxFileDirPickerEvent& event );
		void m_choiceAudioOnChoice( wxCommandEvent& event );
		void m_choiceDisplayOnChoice( wxCommandEvent& event );
		void m_choiceCPLOnChoice( wxCommandEvent& event );

		void m_checkBox_full_screenOnCheckBox( wxCommandEvent& event );
		void m_checkBox_ProgressOnCheckBox( wxCommandEvent& event );
		void m_checkBox_logOnCheckBox( wxCommandEvent& event );
		void m_checkBox_51OnCheckBox( wxCommandEvent& event );
		
		void m_button_runOnButtonClick( wxCommandEvent& event );
		void m_button_quitOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		Run( wxWindow* parent );

		void UpdateCommand();
		void UpdateData(bool sens);
		bool TransferDataToWindow();
		bool TransferDataFromWindow();

		string ChoosenDir;
		char cwd[MAX_PATH];
		string InitialDir;

		wxString m_MyDir;
		wxString m_Com;

		bool m_Back;
		bool m_Log;
		bool m_ProgressBar;
		bool m_Output51;

		vector<wxString> AudioDevice;
		vector<wxString> DisplayDevice;
	//// end generated class members

};

#endif // __Run__
